// Promotion Action Types
export const PROMOTION_ADD_REQUEST = 'PROMOTION_ADD_REQUEST';
export const PROMOTION_ADD_SUCCESS = 'PROMOTION_ADD_SUCCESS';
export const PROMOTION_ADD_FAIL = 'PROMOTION_ADD_FAIL';

export const PROMOTION_LIST_REQUEST = 'PROMOTION_LIST_REQUEST';
export const PROMOTION_LIST_SUCCESS = 'PROMOTION_LIST_SUCCESS';
export const PROMOTION_LIST_FAIL = 'PROMOTION_LIST_FAIL';

export const PROMOTION_UPDATE_REQUEST = 'PROMOTION_UPDATE_REQUEST';
export const PROMOTION_UPDATE_SUCCESS = 'PROMOTION_UPDATE_SUCCESS';
export const PROMOTION_UPDATE_FAIL = 'PROMOTION_UPDATE_FAIL';

export const PROMOTION_DELETE_REQUEST = 'PROMOTION_DELETE_REQUEST';
export const PROMOTION_DELETE_SUCCESS = 'PROMOTION_DELETE_SUCCESS';
export const PROMOTION_DELETE_FAIL = 'PROMOTION_DELETE_FAIL';

export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';